dbt_project:
    target: local
    outputs:
        local:
            type: postgres
            host: localhost
            user: postgres
            password: postgres
            port: 5432
            dbname: elecciones
            schema: prod
